version: "3.9"

services:
  bot:
    image: ghcr.io/Terisback/verifier-bot:latest
    restart: always
    volumes:
      - "./.env:/app/.env"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json